services:
  web:
    build: "./web"
    ports:
      - "3000:3000"
  users:
    build: "./users"
    ports:
      - "3003:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/market-place
  products:
    build: "./products"
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/market-place
  auth:
    build: "./auth"
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/market-place
  db:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - users
      - products
      - auth
